CREATE TABLE users (
id BIGSERIAL NOT NULL PRIMARY KEY,
account_no VARCHAR(255) PRIMARY KEY,
password VARCHAR(25) NOT NULL
);

-- amount, IBAN, swift, time_stamp

CREATE TABLE transactions (
index SERIAL PRIMARY KEY,
amount VARCHAR NOT NULL,
IBAN TEXT NOT NULL,
swift VARCHAR NOT NULL,
time_stamp BIGINT NOT NULL
);

CREATE TABLE sessions (
id VARCHAR(36) PRIMARY KEY,
epoch_time BIGINT NOT NULL
);

